In [116]:
pole = pd.read_csv('Dataset/전국스마트가로등표준데이터.csv',encoding='cp949')
# data = pd.read_csv('Dataset/부산스마트가로등표준데이터.csv')
pole.isnull().sum()

pole.columns

pole['시도명'].unique()

pole['시도명'] = pole['시도명'].replace('14','전라남도')
pole['시도명'].unique()

array(['충청남도', '경기도', '전라남도', '광주광역시', '전라북도', '서울특별시', '강원도', '부산광역시',
       '충청북도'], dtype=object)

In [117]:
find='서울특별시'

시군구명 = list(pole[pole['시도명']==f'{find}']['시군구명'].unique())
시군구명

['강서구', '광진구', '서대문구']

In [138]:
import pandas as pd
import numpy as np
pd.set_option('display.max_row', 500)
import warnings
warnings.filterwarnings('ignore')

검색할시도명 = f'{find}'
검색할시군구명 = '서대문구'


import re
def dong(x):
    import re

    p = re.compile('[가-힣]\S*[읍면동]')

    r = p.findall(x)
    
    return ''.join(r)

import re
def dong1(x):
    import re

    p = re.compile('[가-힣]\S*[면동가]')

    r = p.findall(x)
    
    return ''.join(r)






빼올ui = 검색할시도명
검색할구 = 검색할시군구명

PP = pd.read_csv(f'Dataset/인구밀도/{빼올ui}.csv')
um = PP[PP['시군구명']==검색할구]
u1 = um['읍/면/동'].tolist()
print(u1)
len(u1)

['천연동', '홍제동', '홍은동', '남가좌동', '북가좌동', '충현동', '북아현동', '신촌동', '연희동']

9

In [139]:
data = pd.read_csv('Dataset/서울스마트가로등(위경도채움).csv')
# data = pd.read_csv('Dataset/부산스마트가로등표준데이터.csv',encoding='cp949')
data.isnull().sum()

data.columns

data['시도명'] = 검색할시도명
data['시도명'].unique()

data['시도명'] = data['시도명'].replace('14','전라남도')

data[data['시도명']==검색할시도명]['시군구명'].unique()

data1 = data[data['시도명']==검색할시도명]
detail_1 = data1[data1['시군구명']==검색할시군구명]


detail_1['읍/면/동'] = detail_1['소재지지번주소'].apply(lambda x : dong(x))

detail_1['설치유무'] = 1

get_col = ['시도명','시군구명','읍/면/동','위도','경도','설치유무']
detail_1 = detail_1[get_col]


# u2 = detail_1['읍/면/동'].unique().tolist()
# us = pd.Series(u1)

# detail = pd.DataFrame(us)
# detail['설치유무'] = np.nan
# detail['시도명'] = data[data['시도명']==검색할시도명]['시도명'].unique()[0]
# detail['시군구명'] = data[data['시군구명']==검색할시군구명]['시군구명'].unique()[0]

# def 설치유무(x):
#     y = ''
#     for i in u2 :
#         if x == i :
#             y = 1
#     return y


# detail['설치유무'].update(detail[0].apply(설치유무))
# detail['설치유무'] = detail['설치유무'].replace("",0)
# detail = detail.rename(columns={0:'읍/면/동'})

# detail = detail[['시도명','시군구명','읍/면/동','설치유무','위도','경도']]
# display(detail)
# len(detail)
detail_1.to_csv(f'Dataset/pole/{검색할시도명}{검색할시군구명}스마트폴위경도.csv',index=0)
detail_1

       시도명  시군구명 읍/면/동         위도          경도  설치유무
197  서울특별시  서대문구   홍제동  37.583992  126.949541     1
198  서울특별시  서대문구   홍제동  37.588776  126.944373     1
199  서울특별시  서대문구   홍제동  37.588673  126.944227     1
200  서울특별시  서대문구   홍제동  37.584252  126.948563     1

In [140]:
detail_1

       시도명  시군구명 읍/면/동         위도          경도  설치유무
197  서울특별시  서대문구   홍제동  37.583992  126.949541     1
198  서울특별시  서대문구   홍제동  37.588776  126.944373     1
199  서울특별시  서대문구   홍제동  37.588673  126.944227     1
200  서울특별시  서대문구   홍제동  37.584252  126.948563     1

In [101]:
# real = detail_1[(detail_1['시도명']==f'{검색할시도명}') & (detail_1['시군구명']==f'{검색할시군구명}')][['읍/면/동']]

In [546]:
detail_1[(detail_1['시도명']==f'{검색할시도명}') & (detail_1['시군구명']==f'{검색할시군구명}')]['읍/면/동'].unique()

array(['사직동', '효덕동', '대촌동'], dtype=object)

In [547]:
print(np.array(u1))

['양림동' '방림1동' '방림2동' '봉선1동' '봉선2동' '사직동' '월산동' '월산4동' '월산5동' '백운1동' '백운2동'
 '주월1동' '주월2동' '효덕동' '송암동' '대촌동']

In [548]:
detail[(detail['시도명'] == '광주광역시')&(detail['시군구명']=='남구')]

      시도명 시군구명 읍/면/동  설치유무
0   광주광역시   남구   양림동     0
1   광주광역시   남구  방림1동     0
2   광주광역시   남구  방림2동     0
3   광주광역시   남구  봉선1동     0
4   광주광역시   남구  봉선2동     0
5   광주광역시   남구   사직동     1
6   광주광역시   남구   월산동     0
7   광주광역시   남구  월산4동     0
8   광주광역시   남구  월산5동     0
9   광주광역시   남구  백운1동     0
10  광주광역시   남구  백운2동     0
11  광주광역시   남구  주월1동     0
12  광주광역시   남구  주월2동     0
13  광주광역시   남구   효덕동     1
14  광주광역시   남구   송암동     0
15  광주광역시   남구   대촌동     1

In [549]:
human = pd.read_csv(f'Dataset/인구밀도/{검색할시도명}.csv')
human = human[human['시군구명']==f'{검색할시군구명}']

In [550]:
display(human)
len(human)

      시도명 시군구명 읍/면/동  등록인구수
31  광주광역시   남구   양림동   7592
32  광주광역시   남구  방림1동   7274
33  광주광역시   남구  방림2동   9421
34  광주광역시   남구  봉선1동  15122
35  광주광역시   남구  봉선2동  29602
36  광주광역시   남구   사직동   5669
37  광주광역시   남구   월산동   8005
38  광주광역시   남구  월산4동   9225
39  광주광역시   남구  월산5동   6830
40  광주광역시   남구  백운1동  13019
41  광주광역시   남구  백운2동   6311
42  광주광역시   남구  주월1동  20184
43  광주광역시   남구  주월2동   8698
44  광주광역시   남구   효덕동  47590
45  광주광역시   남구   송암동  19302
46  광주광역시   남구   대촌동   5769

16

In [551]:
df = pd.merge(detail,human,on=['시도명','시군구명','읍/면/동'],how='left')
display(df)
df.to_csv(f'Dataset/human/{검색할시도명}{검색할시군구명}인구총수.csv',index=0)

      시도명 시군구명 읍/면/동  설치유무  등록인구수
0   광주광역시   남구   양림동     0   7592
1   광주광역시   남구  방림1동     0   7274
2   광주광역시   남구  방림2동     0   9421
3   광주광역시   남구  봉선1동     0  15122
4   광주광역시   남구  봉선2동     0  29602
5   광주광역시   남구   사직동     1   5669
6   광주광역시   남구   월산동     0   8005
7   광주광역시   남구  월산4동     0   9225
8   광주광역시   남구  월산5동     0   6830
9   광주광역시   남구  백운1동     0  13019
10  광주광역시   남구  백운2동     0   6311
11  광주광역시   남구  주월1동     0  20184
12  광주광역시   남구  주월2동     0   8698
13  광주광역시   남구   효덕동     1  47590
14  광주광역시   남구   송암동     0  19302
15  광주광역시   남구   대촌동     1   5769

# 스마트 가로등이 없는 지역

In [231]:
import pandas as pd
import numpy as np
pd.set_option('display.max_row', 500)
import warnings
warnings.filterwarnings('ignore')

검색할시도명 = '강원도'
검색할시군구명 = '양양군'

빼올ui = 검색할시도명
검색할구 = 검색할시군구명
PP = pd.read_csv(f'Dataset/인구밀도/{빼올ui}.csv')
um = PP[PP['시군구명']==검색할구]
u1 = um['읍/면/동'].tolist()
u1
len(u1)

6

In [232]:
human = pd.read_csv(f'Dataset/인구밀도/{검색할시도명}.csv')
human = human[human['시군구명']==f'{검색할시군구명}']
display(human)
len(human)

     시도명 시군구명 읍/면/동  등록인구수
182  강원도  양양군   양양읍  11944
183  강원도  양양군    서면   3017
184  강원도  양양군   손양면   2485
185  강원도  양양군   현북면   2648
186  강원도  양양군   현남면   3135
187  강원도  양양군   강현면   4423

6

In [233]:
df = human
df['설치유무'] = 0
df = df[['시도명','시군구명','읍/면/동','설치유무','등록인구수']]
len(df)
display(df)
df.to_csv(f'Dataset/human/{검색할시도명}{검색할시군구명}인구총수.csv',index=0)

     시도명 시군구명 읍/면/동  설치유무  등록인구수
182  강원도  양양군   양양읍     0  11944
183  강원도  양양군    서면     0   3017
184  강원도  양양군   손양면     0   2485
185  강원도  양양군   현북면     0   2648
186  강원도  양양군   현남면     0   3135
187  강원도  양양군   강현면     0   4423

### 자동화

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_row', 500)
import warnings
warnings.filterwarnings('ignore')

검색할시도명 = '서울특별시'
검색할시군구명 = '가평군'

빼올ui = 검색할시도명
검색할구 = 검색할시군구명
PP = pd.read_csv(f'Dataset/인구밀도/{빼올ui}.csv')
자동화 = (PP['시군구명'].unique()).tolist()
자동화

['종로구',
 '중구',
 '용산구',
 '성동구',
 '광진구',
 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',
 '서대문구',
 '마포구',
 '양천구',
 '강서구',
 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구']

### 스마트폴 있는 지역 꼭 제거!

강원도 : 춘천 인제 강릉
경기도 : 가평
광주광역시 : 남구 광산구
전라남도 : 신안
전라북도 : 고창 무주 정읍
충청남도 : 아산
충청북도 : 진천
부산광역시 : 서구
서울 : 강서구 광진구 서대문구

In [312]:
자동화 =['종로구',
 '중구',
 '용산구',
 '성동구',

 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',

 '마포구',
 '양천구',

 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구']

In [313]:
while True:
    for i in 자동화:
        u1 = (PP[PP['시군구명']== i ]['읍/면/동'].unique()).tolist()
        human = pd.read_csv(f'Dataset/인구밀도/{검색할시도명}.csv')
        human = human[human['시군구명']== i ]
        df = human
        df['설치유무'] = 0
        df = df[['시도명','시군구명','읍/면/동','설치유무','등록인구수']]
        df.to_csv(f'Dataset/human/{검색할시도명}{i}인구총수.csv',index=0)
    
    break
    
result = pd.read_csv(f'Dataset/human/{검색할시도명}{i}인구총수.csv')
display(result)

     시도명 시군구명 읍/면/동  설치유무  등록인구수
0  서울특별시  강동구   강일동     0  35778
1  서울특별시  강동구   상일동     0  33345
2  서울특별시  강동구   명일동     0  43932
3  서울특별시  강동구   고덕동     0  48671
4  서울특별시  강동구   암사동     0  69655
5  서울특별시  강동구   성내동     0  68993
6  서울특별시  강동구   둔촌동     0  26675
7  서울특별시  강동구   천호동     0  90081
8  서울특별시  강동구    길동     0  46868

In [ ]:
import pandas as pd
pd.set_option('display.max_row', 500)
import numpy as np

import warnings
warnings.filterwarnings('ignore')

import re
def dong(x):
    import re

    p = re.compile('[가-힣]\S*[읍면동가]')

    r = p.findall(x)
    
    return ''.join(r)

import re
def dong1(x):
    import re

    p = re.compile('[가-힣]\S*[면동가]')

    r = p.findall(x)
    
    return ''.join(r)
검색할시도명='강원도'
검색할시군구명='강릉시'
제공기관명 = f'{검색할시도명} {검색할시군구명}'

빼올ui = 검색할시도명
검색할구 = 검색할시군구명
PP = pd.read_csv(f'Dataset/인구밀도/{빼올ui}.csv')
um = PP[PP['시군구명']==검색할구]
u1 = um['읍/면/동'].tolist()
u1
len(u1)



df= pd.read_excel('dataset/전국어린이보호구역표준데이터-20210801.xls')

df = df.rename(columns=df.iloc[0])
df= df.drop(df.index[0])

df1 = df.loc[df.loc[:,'제공기관명'].str.contains(제공기관명,na=False)]

detail_1 = df1[df1['제공기관명']==제공기관명]


detail_1['읍/면/동'] = detail_1['소재지지번주소'].apply(lambda x : dong1(x))


a= 제공기관명.split(" ")[0]
b= 제공기관명.split(" ")[1]

detail_1['시도명']= a
detail_1['시군구명']= b



a = detail_1[detail_1['읍/면/동']=='']
print(a.head(1))
a['읍/면/동'] = a['읍/면/동'].replace("",'신북읍')
detail_1[detail_1['읍/면/동']==''] = a
child = detail_1[['시도명','시군구명','읍/면/동']]
child['어린이보호구역개수'] = 1
child[child['읍/면/동']=='']



group = child.groupby(['시도명','시군구명','읍/면/동'])
a = group.sum()
a = a.reset_index()
child = a

df = pd.merge(detail,child,on=['시도명','시군구명','읍/면/동'],how='left')
df['어린이보호구역개수'] = df['어린이보호구역개수'].fillna(0)
print(df.isnull().sum())
df.head(1)

df.to_csv(f'Dataset/child/{검색할시도명}{검색할시군구명}어린이보호구역.csv')

In [3]:
result

NameError: name 'result' is not defined

In [4]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)

In [5]:
df

   col1  col2
0     1     3
1     2     4

In [17]:
a = pd.DataFrame(columns=['시설종류', '대상시설명', '소재지도로명주소', '소재지지번주소', '위도', '경도', '관리기관명', '관할경찰서명',
       'CCTV설치여부', 'CCTV설치대수', '보호구역도로폭', '데이터기준일자', '제공기관코드', '제공기관명',
       '읍/면/동', '시도명', '시군구명'])

In [18]:
a

Empty DataFrame
Columns: [시설종류, 대상시설명, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관할경찰서명, CCTV설치여부, CCTV설치대수, 보호구역도로폭, 데이터기준일자, 제공기관코드, 제공기관명, 읍/면/동, 시도명, 시군구명]
Index: []

In [19]:
a = a.append(df)

In [20]:
a

,시설종류,대상시설명,소재지도로명주소,소재지지번주소,위도,경도,관리기관명,관할경찰서명,CCTV설치여부,CCTV설치대수,보호구역도로폭,데이터기준일자,제공기관코드,제공기관명,읍/면/동,시도명,시군구명,col1,col2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0